FROM node:8-alpine

ENV NODE_ENV development

RUN mkdir -p /opt/app/fake-react-site

ADD package.json package-lock.json /opt/app/fake-react-site/

WORKDIR /opt/app/fake-react-site

RUN npm install

CMD ["npm", "start"]
